### ISSUE TITLE
PA Review: Song/Playlist CRUD

### ISSUE THREAD

**Issue by AAlfarho** [AAlfarho/axo-music#18]
The newest build pushed to heroku include
+ Create / Delete Playlists
+ Update Playlist title
+ Add / Delete songs
+ Display artwork.
+ Display dummy image if new playlist or no songs on playlist.
+ Images stored on aws s3.

**Comment by niartenyaw** [comment]
Looks awesome! Comments below:

+ Link to each the playlist should include the album artwork, maybe a square around everything?
+ Same thing for clicking `Playlists` below search.
+ The gradient makes it hard to see what I'm selecting at the top of the page
+ On create new:
    + it says start typing but I can't immediately start. look at input `focus` effects.
    + It would also be nice to be able to submit on enter for the create playlist
    + I think the input box needs some padding
    + after creating, close the modal
    + Add `cancel` button
+ In general, there is a lot of blank space in lists. Space the information out more. everything deserves some padding.
+ move all assets to s3! There should be nothing in your `app/assets` folder
+ Cursor: make sure the cursor doesn't look like it's trying to highlight text in lists (playlist show and add to playlist). make sure it is a `pointer` over all buttons.
+ add and remove buttons could be more descriptive and styled

**Comment by AAlfarho** [comment]
Updates
+ All assets moved to s3.
+ The gradient now has a different background.
+ Nav bar music icon is now clickable and changes color with the text.
+ Autofocus on inputs when creating new playlist.
+ New playlist modal is closed only if successfully created new playlist, otherwise it shows error.
+ Playlist can be updated or created by hitting enter.
+ Blank space on playlist detail was addressed.
+ Buttons for adding an removing songs from playlist are styled properly.

Latest version pushed to heroku.

**Comment by niartenyaw** [comment]
Awesome! Some more notes. Some things were introduced by playing:

+ On hover, you add a border that makes the rest of the list move
+ Not sure where this fits in MVPs, but it would be nice to click on a song
+ Missing cancel buttons for creating and updating playlist
+ Maybe change `update` to `rename` to be clearer?
+ Do you plan on removing the green and yellow borders?
+ Trying to play an empty album throws some errors
+ When going to the playlist show, there are a bunch of actions being dispatched

**Comment by AAlfarho** [comment]
Hey Aaron, here are couple of updates that were pushed in 6700c11177b1812905396965b0d7cae3032d3827 .

+  Green and yellow border will be removed once  those components are ready, ie. when search and playlist/user follow is done.
+ Playing from songs directly is a bonus I would love to have once the rest of the functionality is done.
+ Issue while hovering through songs fixed.
+ I don't really like the idea of having a cancel button it seems unnecessary to me, user can hit "esc", its easier and faster than moving the mouse and click, would it be ok to leave it as it is? Or revisit some fancy eye candy as a enhancement for this?
+ Updated button text from "update" to "rename".
+ Fixed errors when trying to play empty playlist.
+ Fixed the amount of fetches when showing a playlist.

Above changes are now live on heroku.

**Comment by niartenyaw** [comment]
Awesome! One small thing that you can add as an extra issue if you'd like"

+ In the playlist rename, i had to click outside of the text box to be able to `esc`out of it. maybe have a (X esc) circular button in the right corner? Up to you

**Comment by AAlfarho** [comment]
Hey Aaron, i'll keep an eye on that bug you found, I tried it out and I couldn't reproduce it.
I will add a style enhancement for having a little "x" on top ,same way as spotify.
