### ISSUE TITLE
PA Review Continuous Playback

### ISSUE THREAD

**Issue by AAlfarho** [AAlfarho/axo-music#25]
Latest push to Heroku addresses
+ Continuos playback.
+ User can move through the site while still listen to the current song.
+ Playlist will automatically play next song if any.
+ Next and previous song implemented.
   + If hitting prev after 5s of the song being played, it will restart the current song, otherwise it will try to load the prev song.

**All songs seeded belong to the same artist/album : DIIV - Is The Is Are**

**Comment by niartenyaw** [comment]
Awesome!! Looks good to me!
