### ISSUE TITLE
PA Review Follow/Unfollow

### ISSUE THREAD

**Issue by AAlfarho** [AAlfarho/axo-music#38]
+ Follow and unfollow playlists affect the playlists display on the user's collection.
+ Follow and unfollow users will hit the database and all its relations, however this relation will be used as a bonus feature for feed display.
+ Style and proper seed for users addressed.
+ Users will not be able to edit their profiles under the current scope, that will be addressed as a bonus feature, with that in mind, new users will be assigned a "missing picture".

**Comment by AAlfarho** [comment]
There was a hot bug for incorrect avatar image display due to a typo on the jbuilder for user, issue addressed under 8f515926cbbbd9f70f47ca750c75eb9c9fcd6262

**Comment by AAlfarho** [comment]
Live fixed version should be  live on heroku now.

**Comment by niartenyaw** [comment]
Looks great! Comments below:

+ When clicking the Follow or Unfollow button, you may want to blur the button so you don't have the outline
+ May also want to disable the button until the API request returns

**Comment by AAlfarho** [comment]
Thanks for the feedback, i fixed the outline, it was all an issue with my reset, I forgot to add the button to the reset components.

I'll raise an issue for the disabling of buttons until the API request returns.
