### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by AAlfarho** [AAlfarho/axo-music#7]

**Comment by AAlfarho** [comment]
Latest changes are live on heroku.

**Comment by niartenyaw** [comment]
@AAlfarho looks really good! Two small things:
+ Errors could be displayed more prominently, maybe a different position or color
+ When I get errors on the Login page, I can go to the Sign Up page and the errors are still there

**Comment by AAlfarho** [comment]
@niartenyaw thanks for the feedback and the awesome eagle eye.
I moved the errors to a more visible position and change the color according to our theme.
Errors are now being cleared when there's a change on the location path

**Comment by niartenyaw** [comment]
@AAlfarho looks great! A few small things that you might want to consider changing later (feel free to add your own issues for these):

+ the placeholder and text are pretty small
+ You have a lot of vertical room to work with on the page, feel free to space things out more in that direction.
+ I would put `Don't have an account?` and `Sign Up` on the same line
